### ISSUE TITLE
`findPlugin` does not detect plugins with relative paths

### ISSUE THREAD

**Issue by buschtoens** [dfreeman/ember-cli-babel-plugin-helpers#2]
When given a relative plugin path, like `./transforms/strip-empty-class-properties`, `findPlugin` does not detect the plugin.

```
.
├── index.js
├── node_modules
├── package.json
└── transforms
    └── strip-empty-class-properties
        ├── package.json
        └── transform.js
```

Resolving to an absolute path beforehand works.

I can submit a PR for this, when I have some time, but so far the work around is good enough for me 😄

**Comment by dfreeman** [comment]
Taking this package out of the equation, I _think_ using relative paths for Babel plugin configuration is likely to be a footgun. I believe Babel will resolve those paths relative to the current working directory, so a path that works from an addon in development would fail when it's installed in another project.

While we _could_ resolve paths from here,
 - we'd need more information than we currently have (like the root directory of the package adding the plugin)
 - we'd be changing the normal semantics for adding babel plugins

Given that, my leaning would be to stick with the status quo. What do you think?

**Comment by buschtoens** [comment]
Sound sensible! And since there _is_ a way around this by using an absolute path, that issue is closed. 😊
